apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: mockserver
  # This namespace is special and auto-wired to deploy to the local cluster
  namespace: fleet-local
spec:
  repo: "https://github.com/patrickbooth/fleet-mockserver"
  paths:
  - ./resources
  - ./mockserver
  branch: main
