service:
  annotations: {}
  clusterIP: ""
  externalIPs: []
  loadBalancerIP: ""
  loadBalancerSourceRanges: []
  type: ClusterIP
  port: 1080
  nodePort: ""
  test:
    image: radial/busyboxplus:curl

ingress:
  enabled: true
  className: "nginx"
  annotations: {}
  hosts:
    - host: localhost
      paths:
        - path: /mockserver
          pathType: ImplementationSpecific
  tls: []
