apiVersion: v1
kind: ConfigMap
metadata:
  name: mockserver-config
  namespace: mockserver
  labels:
    app.kubernetes.io/name: mockserver
    app.kubernetes.io/version: 5.14.0
data:
  initializerJson.json: |
    [
      {
        "httpRequest": {
        "path": "/mockserver/echo"
        },
        "httpResponseTemplate": {
          "template": "{'statusCode': 200,'body': $request}",
          "templateType": "VELOCITY"
        }
      }
    ]
  mockserver.properties: |-
    mockserver.initializationJsonPath=/config/initializerJson.json
    mockserver.logLevel=WARN
    mockserver.nioEventLoopThreadCount=20
    mockserver.actionHandlerThreadCount=20

